### ISSUE TITLE
Potential issue with chooseBestProteinAccession

### ISSUE THREAD

**Issue by Bucket-Chemist** [APAF-bioinformatics/ProteomeScholaR#56]
This is creating skews in the data for the cleaned accession if there are duplicates

Values getting summed so you end up with large values relative to rest of the dataset

summed_data <- protein_log2_quant_cln |>
               mutate( !!sym(protein_id_column) := purrr::map_chr( !!sym(protein_id_column), \(x){ str_split(x,  delim)[[1]][1] } ) )  |>
               pivot_longer( cols = !matches(protein_id_column)
                            , names_to = "sample_id"
                            , values_to = "temporary_values_choose_accession") |>
               group_by( !!sym(protein_id_column), sample_id ) |>
               summarise( is_na = sum( is.na(temporary_values_choose_accession ))
                          , temporary_values_choose_accession = sum( temporary_values_choose_accession, na.rm=TRUE)
                          , num_values = n() ) |>
                          
 
 Suggest change to mean?
 
 , temporary_values_choose_accession = mean(temporary_values_choose_accession, na.rm=TRUE)
 
 or transform back to linear, take mean and log2 again?
 
 Example of issues downstream below
 
![image](https://github.com/user-attachments/assets/a8f056c3-389f-4d04-9fb3-1447a9ac354b)

![image](https://github.com/user-attachments/assets/1735a5ab-b10e-4544-8761-f354f30fcdd7)

**Comment by Bucket-Chemist** [comment]
cloned out function and tested locally with change to mean()

Data looks alot less funky

![image](https://github.com/user-attachments/assets/6fe44135-5255-4a67-89aa-9c5ad1fd3708)

![image](https://github.com/user-attachments/assets/a9053e19-d129-42df-9e6f-e63ea73068c2)

**Comment by IgnatiusPang** [comment]
I wonder if we can have an option to choose mean or sum and have the default to mean? (Edit: Potential issue with chooseBestProteinAccession #56)

**Comment by IgnatiusPang** [comment]
yeah for some reason when we do choosebestprotein on that dataset it either sums them all up to massive values, or introduces a pc2 of 23596% if swapped to mean (when you run pca on cyclicloess transformed)

**Comment by Bucket-Chemist** [comment]
fixed and implemented mean, median or sum
